#!/bin/bash
set  -e
source helper

IP_PREFIX=$1
START_POINT=$2
END_POINT=$3

if [[ -z $1 ]] || [[ -z $2 ]] || [[ -z $3 ]]; then
  echo "./pingtest [prefix_ip] [start_point] [end_point]"
  echo "|"
  echo "|- example"
  echo "| ./pingtest 192.168.10 1 128"
  echo "|---"
  echo ""
elif [[ $2 -lt 1 ]] || [[ $3 -lt 1 ]] || [[ $(is_valid_ip $IP_PREFIX) -gt 0 ]]; then
  echo "|- invalid prefix, input valid prefix"
  echo "|ex:"
  echo "|-- 10.10.10"
else
  print_title
  [[ $START_POINT -gt $END_POINT ]] && \
    lets_rock_down $IP_PREFIX $START_POINT $END_POINT || \
    lets_rock_up $IP_PREFIX $START_POINT $END_POINT
fi