#!/bin/bash
set  -e
source helper

case $1 in
"-h")
  docs
;;
"-d")
  echo "" > $3
  for i in $(cat $2); do
    # echo $i
    echo $(ping -t 1 $i | grep PING) >> $3
  done
;;
"-r")
  pingtest $2 $3 $4
;;
esac

